<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>grade_certainty_assessment_c2</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="GRADE_certainty_assessment_C2_files/libs/clipboard/clipboard.min.js"></script>
<script src="GRADE_certainty_assessment_C2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="GRADE_certainty_assessment_C2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="GRADE_certainty_assessment_C2_files/libs/quarto-html/popper.min.js"></script>
<script src="GRADE_certainty_assessment_C2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GRADE_certainty_assessment_C2_files/libs/quarto-html/anchor.min.js"></script>
<link href="GRADE_certainty_assessment_C2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GRADE_certainty_assessment_C2_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GRADE_certainty_assessment_C2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GRADE_certainty_assessment_C2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GRADE_certainty_assessment_C2_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="grade-certainty-of-evidence-assessment" class="level1">
<h1>GRADE Certainty-of-Evidence Assessment</h1>
<section id="ptcy-vs-atg-based-prophylaxis-comparison-2-four-primary-outcomes-bsi-supplement" class="level3">
<h3 class="anchored" data-anchor-id="ptcy-vs-atg-based-prophylaxis-comparison-2-four-primary-outcomes-bsi-supplement">PTCy vs ATG-Based Prophylaxis (Comparison 2) — Four Primary Outcomes + BSI Supplement</h3>
<p><em>Prepared: 2026-05-27</em></p>
<hr>
</section>
<section id="framework" class="level2">
<h2 class="anchored" data-anchor-id="framework">Framework</h2>
<p>All evidence derives from observational studies (retrospective cohort and registry analyses); no randomised controlled trial contributed numeric data to any Comparison 2 outcome. GRADE starting certainty is <strong>LOW</strong>. Standard downgrade and upgrade criteria apply per the Comparison 1 assessment (see C1 GRADE document for full framework description). Where Comparison 1 results inform the assessment — for example, the CMV direction reversal — this is noted explicitly.</p>
<p>The Comparison 2 corpus is smaller than Comparison 1 across all outcomes (k = 5–12 vs k = 15–35), and several outcomes (NRM k = 5, aGVHD k = 6) are at the lower boundary of what GRADE conventionally considers assessable. Ratings for these outcomes should be interpreted with this limitation in mind.</p>
<hr>
</section>
<section id="overall-survival-os" class="level2">
<h2 class="anchored" data-anchor-id="overall-survival-os">1. Overall Survival (OS)</h2>
<p><strong>k = 10 paired studies · N = 10,624</strong> <strong>M1: OR 0.69 [0.61–0.78], P(OR &lt; 1) = 100% · τ = 0.56 [0.35–0.96]</strong> <strong>M2 (steroid-adjusted): OR 0.78 [0.68–0.90], P(OR &lt; 1) = 99.9%</strong> <strong>Frequentist: OR 0.53 [0.29–0.96], I² = 90%, τ̂ = 0.85</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Domain</th>
<th>Assessment</th>
<th>Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study design</td>
<td>All retrospective/registry; start LOW</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Risk of bias</strong></td>
<td>Serious: selection bias is plausible — PTCy arms are enriched for haploidentical donors (potentially younger, fitter recipients). M2 partial attenuation (0.69→0.78, 35%) confirms residual confounding but does not abolish the signal. No RCT contributes.</td>
<td>0 (effect survives adjustment; direction of residual confounding uncertain)</td>
</tr>
<tr class="odd">
<td><strong>Inconsistency</strong></td>
<td>Very serious: frequentist I² = 90%, driven by two small studies with extreme ORs (Dybko 2024, OR 0.07; Nykolyszyn 2020, OR 0.17). The Bayesian model regularises this to τ = 0.56 via the half-normal prior, which is defensible but means the heterogeneity assessment depends on the analytic framework. A single study (Penack 2024, n = 8,764) carries 72% of inverse-variance weight, raising concerns about evidence concentration.</td>
<td><strong>−1</strong></td>
</tr>
<tr class="even">
<td><strong>Indirectness</strong></td>
<td>Not serious: direct populations, standard OS endpoint</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Imprecision</strong></td>
<td>Not serious: CrI 0.61–0.78 entirely below null; N = 10,624</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>Publication bias</strong></td>
<td>Not strongly suspected: large registry studies dominate</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Upgrade: cross-comparison coherence</strong></td>
<td>Direction consistent with C1 (OR 0.77 [0.71–0.83]); mediation pattern also consistent (partial attenuation 29% C1, 35% C2). Concordance across two independent comparisons with different comparator regimens strengthens the inference.</td>
<td>+1</td>
</tr>
</tbody>
</table>
<p><strong>Starting certainty:</strong> LOW <strong>Net adjustment:</strong> −1 + 1 = 0 <strong>⊕⊕◯◯ CERTAINTY: LOW</strong></p>
<blockquote class="blockquote">
<p><em>Interpretation: We have low certainty that PTCy reduces overall mortality compared to ATG-based prophylaxis (OR 0.69 [0.61–0.78]). The signal is directionally consistent with Comparison 1 and survives steroid adjustment (M2 OR 0.78). However, the corpus is dominated by a single large registry study (Penack 2024), and two small studies with extreme effect sizes inflate frequentist heterogeneity to I² = 90%. The Bayesian estimate, which regularises these outliers, is considered more appropriate but masks genuine cross-study variability.</em></p>
</blockquote>
<hr>
</section>
<section id="non-relapse-mortality-nrm" class="level2">
<h2 class="anchored" data-anchor-id="non-relapse-mortality-nrm">2. Non-Relapse Mortality (NRM)</h2>
<p><strong>k = 5 paired studies · N = 1,186</strong> <strong>M1: OR 0.65 [0.43–0.97], P(OR &lt; 1) = 98.2% · τ = 0.38 [0.02–0.69]</strong> <strong>M2 (steroid-adjusted, MI): OR 0.76 [0.48–1.16], P(OR &lt; 1) = 90%</strong> <strong>Frequentist: OR 0.61 [0.39–0.95], I² = 0%, τ̂ = 0</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Domain</th>
<th>Assessment</th>
<th>Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study design</td>
<td>All retrospective/registry; start LOW</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Risk of bias</strong></td>
<td>Serious: M2 attenuation (0.65→0.76, 38%) with CrI crossing the null suggests substantial GVHD-mediated confounding, consistent with the complete mediation observed in C1 (M1 OR 0.86 → M2 OR 1.02). Whether the residual C2 benefit (M2 OR 0.76) reflects a genuine direct effect or simply the wider uncertainty at k = 5 cannot be determined.</td>
<td><strong>−1</strong></td>
</tr>
<tr class="odd">
<td><strong>Inconsistency</strong></td>
<td>Not serious: frequentist I² = 0%; Bayesian τ prior-dominated at k = 5 but consistent direction across all five studies</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>Indirectness</strong></td>
<td>Not serious</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Imprecision</strong></td>
<td>Serious: k = 5 with modest total N (1,186); M1 CrI just excludes the null (0.43–0.97) but M2 CrI crosses it (0.48–1.16). Precision is insufficient to distinguish partial from complete mediation.</td>
<td><strong>−1</strong></td>
</tr>
<tr class="even">
<td><strong>Publication bias</strong></td>
<td>Not assessable at k = 5</td>
<td>0</td>
</tr>
</tbody>
</table>
<p><strong>Starting certainty:</strong> LOW <strong>Net adjustment:</strong> −2 (risk of bias, imprecision) <strong>⊕◯◯◯ CERTAINTY: VERY LOW</strong></p>
<blockquote class="blockquote">
<p><em>Interpretation: We have very low certainty about the NRM effect of PTCy vs ATG. The M1 estimate (OR 0.65) is nominally significant, but steroid adjustment attenuates it substantially (M2 OR 0.76, CrI crossing null), reproducing the mediation pattern observed in C1. At k = 5 and N = 1,186, the corpus is too small to determine whether PTCy has a genuine direct NRM advantage over ATG beyond its GVHD-mediated effect. Clinical interpretation should mirror the C1 conclusion: the apparent NRM benefit is likely conditional on GVHD prevention.</em></p>
</blockquote>
<hr>
</section>
<section id="acute-gvhd-grade-iiiv-agvhd" class="level2">
<h2 class="anchored" data-anchor-id="acute-gvhd-grade-iiiv-agvhd">3. Acute GVHD Grade II–IV (aGVHD)</h2>
<p><strong>k = 6 paired studies · N = 784 · all D+100</strong> <strong>M1: OR 0.59 [0.42–0.84], P(OR &lt; 1) = 99.8% · τ = 0.27 [0.01–0.65]</strong> <strong>Frequentist: OR 0.44 [0.22–0.88], I² = 67%, τ̂ = 0.70</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Domain</th>
<th>Assessment</th>
<th>Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study design</td>
<td>All retrospective/registry; start LOW</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Risk of bias</strong></td>
<td>Serious: centre-dependent GVHD grading; possible under-diagnosis in PTCy arms (expectation bias). However, this bias would attenuate the apparent benefit, making the estimate conservative.</td>
<td>0 (direction of residual bias opposes the effect)</td>
</tr>
<tr class="odd">
<td><strong>Inconsistency</strong></td>
<td>Moderate: frequentist I² = 67%, but Bayesian τ = 0.27 with wide CrI [0.01–0.65], reflecting poor information about heterogeneity at k = 6. The discrepancy between frequentist (τ̂ = 0.70) and Bayesian (τ = 0.27) reflects prior influence, not data certainty.</td>
<td><strong>−1</strong></td>
</tr>
<tr class="even">
<td><strong>Indirectness</strong></td>
<td>Not serious: all studies report D+100 aGVHD II–IV, a standard endpoint</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Imprecision</strong></td>
<td>Not serious: CrI 0.42–0.84 entirely below null; P(OR &lt; 1) = 99.8%</td>
<td>0</td>
</tr>
<tr class="even">
<td><strong>Publication bias</strong></td>
<td>Not assessable at k = 6</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Upgrade: confounders oppose</strong></td>
<td>Partially met: if GVHD under-diagnosis in PTCy arms exists, the true effect would be larger than estimated. Cross-comparison coherence with C1 (OR 0.63 [0.54–0.74], k = 24) also supports the signal.</td>
<td>+1</td>
</tr>
</tbody>
</table>
<p><strong>Starting certainty:</strong> LOW <strong>Net adjustment:</strong> −1 + 1 = 0 <strong>⊕⊕◯◯ CERTAINTY: LOW</strong></p>
<blockquote class="blockquote">
<p><em>Interpretation: We have low certainty that PTCy reduces aGVHD grade II–IV compared to ATG (OR 0.59 [0.42–0.84]). The point estimate is concordant with Comparison 1 (C1 OR 0.63), and the CrI is entirely below the null despite the small corpus. The main limitation is poor heterogeneity estimation at k = 6 — frequentist and Bayesian estimates of τ diverge substantially, and neither can be considered reliable. The direction of plausible bias (GVHD under-diagnosis in PTCy arms) would make the true effect larger, not smaller.</em></p>
</blockquote>
<hr>
</section>
<section id="cmv-any-reactivation" class="level2">
<h2 class="anchored" data-anchor-id="cmv-any-reactivation">4. CMV Any-Reactivation</h2>
<p><strong>k = 12 paired studies · N = 1,267</strong> <strong>M1: OR 0.77 [0.60–0.99], P(OR &lt; 1) = 98% · τ = 0.53 [0.30–0.93]</strong> <strong>M2 (steroid-adjusted): OR 0.82 [0.64–1.05], P(OR &lt; 1) = 94%</strong> <strong>Sensitivity (expanded arms, k = 14): OR 0.91 [0.75–1.12], P(OR &lt; 1) = 82%</strong> <strong>Frequentist: OR 0.67 [0.41–1.09], I² = 67%, τ̂ = 0.68</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Domain</th>
<th>Assessment</th>
<th>Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Study design</td>
<td>All retrospective; start LOW</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Risk of bias</strong></td>
<td>Serious: CMV monitoring intensity varies across centres and may differ between PTCy and ATG arms. More intensive surveillance in ATG arms (where T-cell depletion is recognised to increase CMV risk) could inflate ascertainment in the comparator, biasing toward apparent PTCy protection. Donor-type imbalances are common (many PTCy arms are haploidentical while ATG arms are MUD or MRD).</td>
<td>0 (direction of bias uncertain; noted in text)</td>
</tr>
<tr class="odd">
<td><strong>Inconsistency</strong></td>
<td>Serious: I² = 67%, τ = 0.53; heterogeneous timepoint mix (D+100, 1-year, end-of-follow-up); geographic and prophylaxis-era variation</td>
<td><strong>−1</strong></td>
</tr>
<tr class="even">
<td><strong>Indirectness</strong></td>
<td>Not serious: CMV any-reactivation is a standard endpoint</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Imprecision</strong></td>
<td>Serious: CrI 0.60–0.99 just excludes the null in M1, but crosses it in M2 (0.64–1.05) and in the expanded-arm sensitivity (0.75–1.12). The signal is fragile and dependent on analytic decisions (arm classification, covariate adjustment).</td>
<td><strong>−1</strong></td>
</tr>
<tr class="even">
<td><strong>Publication bias</strong></td>
<td>Not strongly suspected</td>
<td>0</td>
</tr>
<tr class="odd">
<td><strong>Upgrade: mechanistic coherence</strong></td>
<td>The direction reversal from C1 (OR 1.41 → C2 OR 0.77) is coherent with the T-cell depletion depth hypothesis: PTCy depletes T cells more than CNI-based regimens but less than ATG, and CMV risk tracks this hierarchy. This cross-comparison coherence is a strong mechanistic signal that would not arise from confounding alone. However, the fragility of the C2 point estimate (sensitivity OR 0.91) tempers the upgrade.</td>
<td>+1 (partial)</td>
</tr>
</tbody>
</table>
<p><strong>Starting certainty:</strong> LOW <strong>Net adjustment:</strong> −2 + 1 = −1 <strong>⊕◯◯◯ CERTAINTY: VERY LOW</strong></p>
<blockquote class="blockquote">
<p><em>Interpretation: We have very low certainty about the magnitude and direction of PTCy’s effect on CMV reactivation compared to ATG. The M1 estimate (OR 0.77) suggests probable protection, but this finding is fragile: steroid adjustment moves the CrI across the null (M2 OR 0.82 [0.64–1.05]), and including PTCy + ATG combination arms attenuates the signal further (OR 0.91 [0.75–1.12]). The most defensible inference is not the specific C2 point estimate but the direction reversal itself: the contrast between C1 (PTCy harmful for CMV vs CNI+MTX/MMF) and C2 (PTCy protective or neutral vs ATG) is mechanistically coherent and supports the conclusion that CMV risk is ordered by depth of T-cell depletion rather than by any intrinsic property of PTCy. This comparative finding has higher certainty than either C2 estimate in isolation.</em></p>
</blockquote>
<hr>
</section>
<section id="bloodstream-infection-bsi-any-pathogen-descriptive-supplement" class="level2">
<h2 class="anchored" data-anchor-id="bloodstream-infection-bsi-any-pathogen-descriptive-supplement">5. Bloodstream Infection (BSI, any pathogen) — Descriptive Supplement</h2>
<p><strong>k = 3 paired studies · N = 613</strong> <strong>Mantel-Haenszel fixed-effect: OR 2.03 [1.33–3.09], p = 0.001 · I² = 69%</strong></p>
<p>A formal GRADE assessment is not performed for BSI in Comparison 2, as the corpus of three studies is below the conventional minimum for structured certainty rating. The following limitations are noted for context:</p>
<ul>
<li><strong>Definitional heterogeneity:</strong> Two studies (Meyer 2025, Berro 2021) used any positive blood culture; one (Bordat 2026) restricted to severe infections requiring ICU admission or resulting in death. These are not equivalent constructs.</li>
<li><strong>Timepoint mismatch:</strong> D+100 (2 studies) vs 1-year (1 study).</li>
<li><strong>Donor-type confound:</strong> The dominant study (Meyer 2025, 72% of weight) had 54% haploidentical donors in the PTCy arm vs 100% MUD in the ATG arm.</li>
<li><strong>Direction consistent with C1</strong> (C1 OR 2.39 [1.85–3.10], k = 6), but the C1 corpus also carried a VERY LOW certainty rating.</li>
</ul>
<p>If a rating were forced, it would be <strong>⊕◯◯◯ VERY LOW</strong> at best, driven by very serious risk of bias (definitional and population heterogeneity), very serious imprecision (k = 3), and inability to assess publication bias.</p>
<hr>
</section>
<section id="summary-table" class="level2">
<h2 class="anchored" data-anchor-id="summary-table">Summary Table</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>k</th>
<th>N</th>
<th>OR [95% CrI]</th>
<th>Posterior P</th>
<th>Certainty</th>
<th>Key limitation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Overall survival</strong></td>
<td>10</td>
<td>10,624</td>
<td>0.69 [0.61–0.78]</td>
<td>P(&lt;1) = 100%</td>
<td>⊕⊕◯◯ <strong>LOW</strong></td>
<td>I² = 90% (freq); evidence concentrated in one registry</td>
</tr>
<tr class="even">
<td><strong>Non-relapse mortality</strong></td>
<td>5</td>
<td>1,186</td>
<td>0.65 [0.43–0.97]</td>
<td>P(&lt;1) = 98%</td>
<td>⊕◯◯◯ <strong>VERY LOW</strong></td>
<td>k = 5; M2 mediation; CrI fragile</td>
</tr>
<tr class="odd">
<td><strong>aGVHD grade II–IV</strong></td>
<td>6</td>
<td>784</td>
<td>0.59 [0.42–0.84]</td>
<td>P(&lt;1) = 100%</td>
<td>⊕⊕◯◯ <strong>LOW</strong></td>
<td>k = 6; τ poorly estimated</td>
</tr>
<tr class="even">
<td><strong>CMV reactivation</strong></td>
<td>12</td>
<td>1,267</td>
<td>0.77 [0.60–0.99]</td>
<td>P(&lt;1) = 98%</td>
<td>⊕◯◯◯ <strong>VERY LOW</strong></td>
<td>CrI fragile to adjustment/sensitivity; direction reversal from C1 is the key finding</td>
</tr>
<tr class="odd">
<td><strong>BSI any pathogen</strong></td>
<td>3</td>
<td>613</td>
<td>2.03 [1.33–3.09]†</td>
<td>p = 0.001</td>
<td>(⊕◯◯◯)‡</td>
<td>k = 3; definitional heterogeneity; donor confound</td>
</tr>
</tbody>
</table>
<p>†Mantel-Haenszel fixed-effect; not Bayesian. ‡Informal rating; formal GRADE not performed at k = 3.</p>
<p><em>⊕ = present; ◯ = absent. Certainty levels: HIGH (⊕⊕⊕⊕), MODERATE (⊕⊕⊕◯), LOW (⊕⊕◯◯), VERY LOW (⊕◯◯◯).</em></p>
<hr>
</section>
<section id="grade-narrative-summary-comparison-2" class="level2">
<h2 class="anchored" data-anchor-id="grade-narrative-summary-comparison-2">GRADE Narrative Summary — Comparison 2</h2>
<p>Certainty of evidence in Comparison 2 is LOW for OS and aGVHD, and VERY LOW for NRM, CMV, and BSI — generally one tier lower than the corresponding Comparison 1 ratings, reflecting the smaller corpora and greater analytic fragility.</p>
<p>Three observations are methodologically notable:</p>
<ol type="1">
<li><p><strong>Cross-comparison coherence strengthens OS and aGVHD inferences.</strong> Both outcomes show directionally consistent, mechanistically expected effects across two independent comparisons with different control regimens (C1: CNI+MTX/MMF; C2: ATG). The mediation pattern for OS (partial attenuation) and NRM (substantial attenuation) also replicates. While GRADE does not formally recognise cross-comparison consistency as an upgrade criterion, it substantially reduces the probability that the observed signals are artefacts of a single comparator-specific confounding structure.</p></li>
<li><p><strong>The CMV direction reversal is more informative than either point estimate alone.</strong> The C2 CMV signal (OR 0.77) is individually fragile. However, the reversal from C1 (OR 1.41) to C2 (OR 0.77) is robust to the specific C2 point estimate: any value below ~1.0 in C2 confirms a qualitative shift in direction. This cross-comparison contrast provides moderate-certainty evidence that CMV risk is ordered by depth of T-cell depletion, even though the individual C2 estimate has very low certainty.</p></li>
<li><p><strong>BSI and IFI remain data-poor.</strong> Neither outcome has sufficient Comparison 2 data for meaningful inference. Dedicated prospective studies of infection outcomes in PTCy vs ATG cohorts remain a priority evidence gap.</p></li>
</ol>
<hr>
<p><em>All Bayesian estimates from brms 2.23.0 (rstan backend). Mantel-Haenszel estimate from metafor 5.0-1. GRADE applied per the GRADE Handbook (Schünemann et al.) and the GRADE working group guidance for meta-analyses of observational studies.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>